// Mocks generated by Mockito 5.4.5 from annotations
// in nemorixpay/test/features/transactions/domain/usecases/get_transactions_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nemorixpay/core/errors/failures.dart' as _i5;
import 'package:nemorixpay/features/transactions/domain/entities/transaction_list_item_data.dart'
    as _i6;
import 'package:nemorixpay/features/transactions/domain/repositories/transactions_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TransactionsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionsRepository extends _i1.Mock
    implements _i3.TransactionsRepository {
  MockTransactionsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>>
  getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.TransactionListItemData>>(
                this,
                Invocation.method(#getTransactions, []),
              ),
            ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>>
  refreshTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTransactions, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.TransactionListItemData>>(
                this,
                Invocation.method(#refreshTransactions, []),
              ),
            ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>
          >);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TransactionListItemData>>
  getTransactionDetails(String? transactionHash) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionDetails, [transactionHash]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, _i6.TransactionListItemData>
            >.value(
              _FakeEither_0<_i5.Failure, _i6.TransactionListItemData>(
                this,
                Invocation.method(#getTransactionDetails, [transactionHash]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.TransactionListItemData>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>>
  filterTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#filterTransactions, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.TransactionListItemData>>(
                this,
                Invocation.method(#filterTransactions, []),
              ),
            ),
          )
          as _i4.Future<
            _i2.Either<_i5.Failure, List<_i6.TransactionListItemData>>
          >);
}
