// Mocks generated by Mockito 5.4.5 from annotations
// in nemorixpay/test/shared/stellar/domain/services/wallet_verification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nemorixpay/shared/common/data/models/asset_model.dart' as _i4;
import 'package:nemorixpay/shared/stellar/data/datasources/stellar_secure_storage_datasource.dart'
    as _i6;
import 'package:nemorixpay/shared/stellar/data/models/stellar_account_model.dart'
    as _i3;
import 'package:nemorixpay/shared/stellar/data/providers/stellar_account_provider.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StellarAccountProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockStellarAccountProvider extends _i1.Mock
    implements _i2.StellarAccountProvider {
  MockStellarAccountProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set userId(String? _userId) => super.noSuchMethod(
    Invocation.setter(#userId, _userId),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasValidAccount =>
      (super.noSuchMethod(
            Invocation.getter(#hasValidAccount),
            returnValue: false,
          )
          as bool);

  @override
  void setCurrentAccount(_i3.StellarAccountModel? account) =>
      super.noSuchMethod(
        Invocation.method(#setCurrentAccount, [account]),
        returnValueForMissingStub: null,
      );

  @override
  void updateSecretKey(String? newSecretKey) => super.noSuchMethod(
    Invocation.method(#updateSecretKey, [newSecretKey]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePublicKey(String? newPublicKey) => super.noSuchMethod(
    Invocation.method(#updatePublicKey, [newPublicKey]),
    returnValueForMissingStub: null,
  );

  @override
  void updateMnemonic(String? newMnemonic) => super.noSuchMethod(
    Invocation.method(#updateMnemonic, [newMnemonic]),
    returnValueForMissingStub: null,
  );

  @override
  void updateBalance(double? newBalance) => super.noSuchMethod(
    Invocation.method(#updateBalance, [newBalance]),
    returnValueForMissingStub: null,
  );

  @override
  void updateAssets(List<_i4.AssetModel>? newAssets) => super.noSuchMethod(
    Invocation.method(#updateAssets, [newAssets]),
    returnValueForMissingStub: null,
  );

  @override
  void clearCurrentAccount() => super.noSuchMethod(
    Invocation.method(#clearCurrentAccount, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> syncWithSecureStorage() =>
      (super.noSuchMethod(
            Invocation.method(#syncWithSecureStorage, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [StellarSecureStorageDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStellarSecureStorageDataSource extends _i1.Mock
    implements _i6.StellarSecureStorageDataSource {
  MockStellarSecureStorageDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> savePrivateKey({
    required String? publicKey,
    required String? privateKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savePrivateKey, [], {
              #publicKey: publicKey,
              #privateKey: privateKey,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> savePublicKey({
    required String? publicKey,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savePublicKey, [], {
              #publicKey: publicKey,
              #userId: userId,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String?> getPrivateKey({required String? publicKey}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKey, [], {#publicKey: publicKey}),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getPublicKey({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKey, [], {#userId: userId}),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> hasPrivateKey({required String? publicKey}) =>
      (super.noSuchMethod(
            Invocation.method(#hasPrivateKey, [], {#publicKey: publicKey}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasPublicKey({required String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#hasPublicKey, [], {#userId: userId}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteAllKeys() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllKeys, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deletePrivateKey({required String? publicKey}) =>
      (super.noSuchMethod(
            Invocation.method(#deletePrivateKey, [], {#publicKey: publicKey}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<String>> getAllPublicKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPublicKeys, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);
}
