// Mocks generated by Mockito 5.4.5 from annotations
// in nemorixpay/test/features/settings/data/repositories/settings_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:nemorixpay/features/settings/data/datasources/settings_local_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SettingsLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsLocalDatasource extends _i1.Mock
    implements _i2.SettingsLocalDatasource {
  MockSettingsLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> getDarkModePreference() =>
      (super.noSuchMethod(
            Invocation.method(#getDarkModePreference, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> saveDarkModePreference(bool? isDarkMode) =>
      (super.noSuchMethod(
            Invocation.method(#saveDarkModePreference, [isDarkMode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> toggleDarkMode() =>
      (super.noSuchMethod(
            Invocation.method(#toggleDarkMode, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String> getLanguagePreference() =>
      (super.noSuchMethod(
            Invocation.method(#getLanguagePreference, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#getLanguagePreference, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> saveLanguagePreference(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#saveLanguagePreference, [languageCode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
